# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly_history',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
