# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170224_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone_info',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fly_history',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
